<center><h1> Série de Travaux Pratiques N° 7 - Machine Learning </h1></center>
<center><h2> K-Nearest Neighbor and Decision Tree</h2></center>

---



Pour ce TP, on utilisera le **dataset IRIS**. Ce dernier est une base de données regroupant les caractéristiques de **trois espèces de fleurs d’Iris, à savoir Setosa, Versicolour et Virginica**. Chaque ligne de ce jeu de données est une observation des caractéristiques d’une fleur d’Iris. Ce dataset décrit les espèces d’Iris par quatre propriétés : longueur et largeur de sépales ainsi que longueur et largeur de pétales. La base de données comporte 150 observations (50 observations par espèce).

# **Partie I : K-Nearest Neighbor**

# **Questions :**

1- Importer les packages nécessaires

2- Lire l'ensemble de données dans le dataframe pandas

3- Afficher et explorer l'ensemble de données "**iris.csv**"

4- Extraire les variables d'entrée X

5- Extraire les variables de sortie y

6- Diviser le dataset en Train / Test

7- Mise à l'échelle des fonctionnalités avec Transform()

8- Définir votre modèle **KNN**

9- Entraîner le modèle

10- Prédiction sur l'ensemble de test

11- Évaluation du modèle à l'aide de métriques

In [1]:
# IRIS Dataset : KNN


# 1- Importer les packages nécessaires
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# 2- Lire l'ensemble de données dans le dataframe pandas
dataknn=pd.read_csv("iris.csv")

# 3- Afficher et explorer l'ensemble de données "**iris.csv**"
print(dataknn.head())
print(dataknn.info())

# 4- Extraire les variables d'entrée X
X=dataknn.drop('variety', axis=1)    #X=dataknn.iloc[:,:-1] 

# 5- Extraire les variables de sortie y
y=dataknn['variety']                #y=dataknn.iloc[:,-1]

# 6- Diviser le dataset en Train / Test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =train_test_split(X,y,random_state=104,test_size=0.3,shuffle=True)

# 7- Mise à l'échelle des fonctionnalités avec Transform()
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X_train)
X_train =scaler.transform(X_train)
X_test =scaler.transform(X_test)

# 8- Définir votre modèle KNN
from sklearn.neighbors import KNeighborsClassifier
classifier= KNeighborsClassifier(n_neighbors=5)

# 9- Entraîner le modèle
classifier.fit(X_train,y_train)

# 10- Prédiction sur l'ensemble de test
y_pred= classifier.predict(X_test)

# 11- Évaluation du modèle à l'aide de métriques
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
y_pred=classifier.predict(X_test)
accuracy=accuracy_score(y_test,y_pred)
conf_matrix=confusion_matrix(y_test,y_pred)
class_report= classification_report(y_test,y_pred)
print(f"Accuracy :{accuracy*100:.2f}%")
print("Confusion Matrix")
print(conf_matrix)
print("classification report")
print(class_report)

#12- Changer le K = {5, 10, 20, 30, 40}, que remarquez-vous?
#l'accuracy change avec la variation de K

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None
Accuracy :97.78%
Confusion Matrix
[[20  0  0]
 [ 0 17  0]
 [ 0  1  7]]
classification report
              precision    recall  f1-score   support

      

# **Partie II : Decision Trees**

# **Questions :**

1- Importer les packages nécessaires

2- Lire l'ensemble de données dans le dataframe pandas

3- Afficher et explorer l'ensemble de données "**iris.csv**"

4- Extraire les variables d'entrée X

5- Extraire les variables de sortie y

6- Diviser le dataset en Train / Test

7- Mise à l'échelle des fonctionnalités avec Transform()

8- Définir votre modèle **Decision Tree**

9- Entraîner le modèle

10- Prédiction sur l'ensemble de test

11- Évaluation du modèle à l'aide de métriques

In [2]:
# IRIS Dataset : Decision Tree


# 1- Importer les packages nécessaires
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 2- Lire l'ensemble de données dans le dataframe pandas
datadt=pd.read_csv("iris.csv")

# 3- Afficher et explorer l'ensemble de données "iris.csv"
datadt.head()

# 4- Extraire les variables d'entrée X
X=datadt.drop('variety', axis=1)

# 5- Extraire les variables de sortie y
y=datadt['variety']

# 6- Diviser le dataset en Train / Test
from sklearn.model_selection import train_test_split
X_train_dt, X_test_dt, y_train_dt, y_test_dt =train_test_split(X,y,random_state=420,test_size=0.3,shuffle=True)

# 7- Mise à l'échelle des fonctionnalités avec Transform()
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X_train_dt)
X_train_dt =scaler.transform(X_train_dt)
X_test_dt =scaler.transform(X_test_dt)

# 8- Définir votre modèle Decision Tree
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()

# 9- Entraîner le modèle
dt.fit(X_train_dt,y_train_dt)

# 10- Prédiction sur l'ensemble de test
y_pred_dt=dt.predict(X_test_dt)

# 11- Évaluation du modèle à l'aide de métriques
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

accuracy_dt=accuracy_score(y_test_dt,y_pred_dt)
conf_matrix_dt=confusion_matrix(y_test_dt,y_pred_dt)
class_report_dt= classification_report(y_test_dt,y_pred_dt)
print(f"Accuracy :{accuracy_dt*100:.2f}%")
print("Confusion Matrix")
print(conf_matrix_dt)
print("classification report")
print(class_report_dt)

Accuracy :95.56%
Confusion Matrix
[[15  0  0]
 [ 0 18  2]
 [ 0  0 10]]
classification report
              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        15
  Versicolor       1.00      0.90      0.95        20
   Virginica       0.83      1.00      0.91        10

    accuracy                           0.96        45
   macro avg       0.94      0.97      0.95        45
weighted avg       0.96      0.96      0.96        45

