<center><h1> Corréction Série de Travaux Pratiques N° 6 - Machine Learning </h1></center>
<center><h2> Regression Logistique</h2></center>

---



# **Partie I : Regression Logistique**

Vous trouverez ci-joint un exemple d'utilisation d'algorithme de regréssion logistique avec les quatres étapes principales.

In [39]:
# Step 1: Import packages, functions
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

# Step 2: Get data
x = np.arange(10).reshape(-1, 1)
y = np.array([0, 1, 0, 0, 1, 1, 1, 1, 1, 1])

# Step 3: Create a model and train it
model = LogisticRegression(solver='liblinear', C=10.0, random_state=0, max_iter=100)
model.fit(x, y)

# Step 4: Evaluate the model
p_pred = model.predict_proba(x) #prediction de probabilite de chaque classe ex:p_pred: [[0.81999686 0.18000314] 1ere pour classe 0 et 2eme pour classe 1
y_pred = model.predict(x)
score_ = model.score(x, y)
conf_m = confusion_matrix(y, y_pred)
report = classification_report(y, y_pred) #accuracy= Nb Prediction Vraies/Nb total Vrai . Nb d'exemples dataset
#precision= Nb PredVraie/Nb Prediction Totale 

In [40]:
print('x:', x)
print('y:', y)
print('intercept:', model.intercept_)
print('coef:', model.coef_)
print('p_pred:', p_pred)
print('y_pred:', y_pred)
print('score_:', score_)
print('conf_m:', conf_m)
print('report:', report)

x: [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
y: [0 1 0 0 1 1 1 1 1 1]
intercept: [-1.51632619]
coef: [[0.703457]]
p_pred: [[0.81999686 0.18000314]
 [0.69272057 0.30727943]
 [0.52732579 0.47267421]
 [0.35570732 0.64429268]
 [0.21458576 0.78541424]
 [0.11910229 0.88089771]
 [0.06271329 0.93728671]
 [0.03205032 0.96794968]
 [0.0161218  0.9838782 ]
 [0.00804372 0.99195628]]
y_pred: [0 0 0 1 1 1 1 1 1 1]
score_: 0.8
conf_m: [[2 1]
 [1 6]]
report:               precision    recall  f1-score   support

           0       0.67      0.67      0.67         3
           1       0.86      0.86      0.86         7

    accuracy                           0.80        10
   macro avg       0.76      0.76      0.76        10
weighted avg       0.80      0.80      0.80        10



# **Partie II : Classification Binaire**

L'objectif de l'ensemble de données "**diabetes.csv**" est de prédire, sur la base de mesures diagnostiques, si un patient **souffre de diabète ou pas**.

Ce dataset contient les caractéristiques suivants

**Grossesses**: Nombre de fois enceintes.

**Glucose**: concentration plasmatique de glucose à 2 heures lors d'un test oral de tolérance au glucose.

**Pression artérielle** : tension artérielle diastolique (mm Hg).

**Épaisseur de la peau** : épaisseur du pli cutané du triceps (mm).

**Insuline** : insuline sérique de 2 heures (mu U/ml).

**IMC** : Indice de masse corporelle (poids en kg/(taille en m)^2).

**DiabetesPedigreeFunction** : fonction généalogique du diabète.

**Âge** : Âge (ans).

**Résultat** : variable de classe (0 ou 1).

### **Questions :**

Étape 1 : Importer et afficher et explorer l'ensemble de données "**diabetes.csv**"

Étape 2 : Créer dépendante d'une variable indépendante et stockée sur les variables X et Y.

Étape 3 : Transformer les chaînes en entier.

Étape 4 : Divisez les données en ensembles d'entrainement et de test.

Étape 5 : Définir l'algorithme de régression logistique.

Étape 6 :Tester les données de test en utilisant votre modèle.

Étape 7 : Évaluation du modèle.

Étape 8 : Prédire avec de nouvelles valeurs.

In [41]:
# Binary Classification : Diabetes

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

diab=pd.read_csv("diabetes.csv")
X=diab.iloc[:,:-1]
y=diab.iloc[:,-1] 


#Étape 4 : Divisez les données en ensembles d'entrainement et de test.
X_train, X_test, y_train, y_test =train_test_split(X,y,random_state=104,test_size=0.25,shuffle=True)

#Étape 5 : Définir l'algorithme de régression logistique.
model=LogisticRegression(max_iter=1000)
model.fit(X_train,y_train)

#Étape 6 :Tester les données de test en utilisant votre modèle.
y_pred=model.predict(X_test)
accuracy=accuracy_score(y_test,y_pred) #+ accu ==> max iter ++ et train_size++ et penalisation(regularization )
conf_matrix=confusion_matrix(y_test,y_pred)
class_report= classification_report(y_test,y_pred)
print(f"Accuracy :{accuracy*100:.2f}%")
print("Confusion Matrix")
print(conf_matrix)
print("classification report")
print(class_report)

Accuracy :79.69%
Confusion Matrix
[[114  14]
 [ 25  39]]
classification report
              precision    recall  f1-score   support

           0       0.82      0.89      0.85       128
           1       0.74      0.61      0.67        64

    accuracy                           0.80       192
   macro avg       0.78      0.75      0.76       192
weighted avg       0.79      0.80      0.79       192



In [42]:
 # Se connecter
# from google.colab import drive
# drive.mount('/content/drive')

In [43]:
# cd drive/My Drive/Colab Notebooks

# **Partie II : Classification Multi-Classe**

Pour cette partie, on utilisera le **dataset IRIS**. Ce dernier est une base de données regroupant les caractéristiques de **trois espèces de fleurs d’Iris, à savoir Setosa, Versicolour et Virginica**. Chaque ligne de ce jeu de données est une observation des caractéristiques d’une fleur d’Iris. Ce dataset décrit les espèces d’Iris par quatre propriétés : longueur et largeur de sépales ainsi que longueur et largeur de pétales. La base de données comporte 150 observations (50 observations par espèce).

### **Questions :**

Étape 1 : Importer, afficher et explorer l'ensemble de données "**iris.csv**"

Étape 2 : Créer dépendante d'une variable indépendante et stockée sur les variables X et Y.

Étape 3 : Transformer les chaînes en entier.

Étape 4 : Divisez les données en ensembles d'entrainement et de test.

Étape 5 : Définir l'algorithme de régression logistique.

Étape 6 :Tester les données de test en utilisant votre modèle.

Étape 7 : Évaluation du modèle.

Étape 8 : Prédire avec de nouvelles valeurs.

In [44]:
# Multi-Class Classification : IRIS Dataset
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder as le
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

data_iris=pd.read_csv("iris.csv")
data_iris.head()

x1=data_iris.drop(["variety"], axis=1)
y1=data_iris["variety"]
x1.head()

y1=le().fit_transform(y1)

X_train, X_test, y_train, y_test = train_test_split(x1,y1,random_state=101, test_size=0.25, shuffle=True)

model=LogisticRegression(max_iter=100)
model.fit(X_train,y_train)

y_pred=model.predict(X_test)
accuracy=accuracy_score(y_test,y_pred)
conf_matrix=confusion_matrix(y_test,y_pred)
class_report= classification_report(y_test,y_pred)
print(f"Accuracy :{accuracy*100:.2f}%")
print("Confusion Matrix")
print(conf_matrix)
print("classification report")
print(class_report)

Accuracy :100.00%
Confusion Matrix
[[10  0  0]
 [ 0 17  0]
 [ 0  0 11]]
classification report
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        17
           2       1.00      1.00      1.00        11

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38

